version: "3.3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"

  service2:
    container_name: service2
    build:
      context: ./service2
      dockerfile: Dockerfile
    depends_on:
      - "postgres"
    restart: always
    ports:
      - "8081:8081"

  service1:
    container_name: service1
    build:
      context: ./service1
      dockerfile: Dockerfile
    depends_on:
      - "service2"
    restart: always
    ports:
      - "8082:8082"

  gateway:
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    depends_on:
      - "service1"
    restart: always
    ports:
      - "8085:8085"
